[package]
name = "lisp-ast-viewer"
version = "0.1.0"
authors = ["divy-work <dj.srivastava23@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codespan = "*"